package com.myspace.islamiccarmurabaha;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PdfRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("Company")
	private java.lang.String company;
	@org.kie.api.definition.type.Label("Total_income")
	private java.lang.String total_income;
	@org.kie.api.definition.type.Label("Statement_number")
	private java.lang.String statement_number;
	@org.kie.api.definition.type.Label("Invoice_number")
	private java.lang.String invoice_number;
	@org.kie.api.definition.type.Label("Car_price")
	private java.lang.String car_price;
	@org.kie.api.definition.type.Label("Car_type")
	private java.lang.String car_type;

	@org.kie.api.definition.type.Label("trafficCenter")
	private java.lang.String trafficCenter;

	@org.kie.api.definition.type.Label(value = "car_manufacturer")
	private java.lang.String car_manufacturer;

	@org.kie.api.definition.type.Label(value = "car_engineCapacity")
	private java.lang.String car_engineCapacity;

	@org.kie.api.definition.type.Label(value = "car_ChassisNumber")
	private java.lang.String car_ChassisNumber;

	@org.kie.api.definition.type.Label(value = "car_color")
	private java.lang.String car_color;

	@org.kie.api.definition.type.Label(value = "car_year")
	private java.lang.String car_year;

	@org.kie.api.definition.type.Label(value = "car_milage")
	private java.lang.String car_milage;

	public PdfRequest() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCompany() {
		return this.company;
	}

	public void setCompany(java.lang.String company) {
		this.company = company;
	}

	public java.lang.String getTotal_income() {
		return this.total_income;
	}

	public void setTotal_income(java.lang.String total_income) {
		this.total_income = total_income;
	}

	public java.lang.String getStatement_number() {
		return this.statement_number;
	}

	public void setStatement_number(java.lang.String statement_number) {
		this.statement_number = statement_number;
	}

	public java.lang.String getInvoice_number() {
		return this.invoice_number;
	}

	public void setInvoice_number(java.lang.String invoice_number) {
		this.invoice_number = invoice_number;
	}

	public java.lang.String getCar_price() {
		return this.car_price;
	}

	public void setCar_price(java.lang.String car_price) {
		this.car_price = car_price;
	}

	public java.lang.String getCar_type() {
		return this.car_type;
	}

	public void setCar_type(java.lang.String car_type) {
		this.car_type = car_type;
	}

	public java.lang.String getTrafficCenter() {
		return this.trafficCenter;
	}

	public void setTrafficCenter(java.lang.String trafficCenter) {
		this.trafficCenter = trafficCenter;
	}

	public java.lang.String getCar_manufacturer() {
		return this.car_manufacturer;
	}

	public void setCar_manufacturer(java.lang.String car_manufacturer) {
		this.car_manufacturer = car_manufacturer;
	}

	public java.lang.String getCar_engineCapacity() {
		return this.car_engineCapacity;
	}

	public void setCar_engineCapacity(java.lang.String car_engineCapacity) {
		this.car_engineCapacity = car_engineCapacity;
	}

	public java.lang.String getCar_ChassisNumber() {
		return this.car_ChassisNumber;
	}

	public void setCar_ChassisNumber(java.lang.String car_ChassisNumber) {
		this.car_ChassisNumber = car_ChassisNumber;
	}

	public java.lang.String getCar_color() {
		return this.car_color;
	}

	public void setCar_color(java.lang.String car_color) {
		this.car_color = car_color;
	}

	public java.lang.String getCar_year() {
		return this.car_year;
	}

	public void setCar_year(java.lang.String car_year) {
		this.car_year = car_year;
	}

	public java.lang.String getCar_milage() {
		return this.car_milage;
	}

	public void setCar_milage(java.lang.String car_milage) {
		this.car_milage = car_milage;
	}

	public PdfRequest(java.lang.String name, java.lang.String id,
			java.lang.String address, java.lang.String company,
			java.lang.String total_income, java.lang.String statement_number,
			java.lang.String invoice_number, java.lang.String car_price,
			java.lang.String car_type, java.lang.String trafficCenter,
			java.lang.String car_manufacturer,
			java.lang.String car_engineCapacity,
			java.lang.String car_ChassisNumber, java.lang.String car_color,
			java.lang.String car_year, java.lang.String car_milage) {
		this.name = name;
		this.id = id;
		this.address = address;
		this.company = company;
		this.total_income = total_income;
		this.statement_number = statement_number;
		this.invoice_number = invoice_number;
		this.car_price = car_price;
		this.car_type = car_type;
		this.trafficCenter = trafficCenter;
		this.car_manufacturer = car_manufacturer;
		this.car_engineCapacity = car_engineCapacity;
		this.car_ChassisNumber = car_ChassisNumber;
		this.car_color = car_color;
		this.car_year = car_year;
		this.car_milage = car_milage;
	}

}